# Generated by Django 4.2.1 on 2023-05-15 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('descriptions', models.CharField(max_length=244)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('year_of_birth', models.PositiveIntegerField(null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('pesel', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta')], default='M')),
                ('weight', models.IntegerField(null=True)),
                ('growth', models.IntegerField(null=True)),
                ('description_of_diseases', models.TextField()),
                ('drugs_list', models.TextField()),
                ('medicament', models.ManyToManyField(to='patients_app.medicament')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('patients', models.ManyToManyField(to='patients_app.patients')),
            ],
        ),
        migrations.CreateModel(
            name='DateAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_add', models.DateTimeField(null=True)),
                ('patients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patients_app.patients')),
            ],
        ),
    ]
