# Generated by Django 4.2.1 on 2023-05-23 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='medicament',
            field=models.ManyToManyField(related_name='patients', to='patients_app.medicament'),
        ),
    ]
