# Generated by Django 4.2.1 on 2023-05-24 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0002_alter_patients_medicament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=800)),
                ('image', models.ImageField(upload_to='static/')),
            ],
        ),
    ]
