# Generated by Django 4.2.1 on 2023-05-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_app', '0004_doctors_email_prescription_medicalnote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcomponent',
            name='patients',
            field=models.ManyToManyField(related_name='medical_component', to='patients_app.patients'),
        ),
    ]
